services:
  deno:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
      - ./entrypoint.sh:/entrypoint.sh
      - deno-dir:/deno-dir
    environment:
      - DENO_DIR=/deno-dir
      - UID=1000
      - UNAME=user
      - GID=1000
      - GNAME=user
    entrypoint: /entrypoint.sh

volumes:
  deno-dir:
